language: node_js
group: edge
sudo: required
services:
  - mongodb
  - docker
node_js:
  - "4.4.3"
  - "6.9.1"
before_install:
 - npm install -g grunt@0.4.5
 - npm install -g grunt-cli
 - npm install 
install: 
  - npm install grunt-cli
  - npm install grunt@0.4.5
  - npm install grunt-shell
  - npm install fh-build -g
  - npm ls
  - fh-build template
  
